const genshinCharacters = [
  // Mondstadt
  {
    name: "Albedo",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Sword",
    type: "Sub-DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Albedo.png",
    altText: "Albedo, the Chief Alchemist of the Knights of Favonius",
  },
  {
    name: "Amber",
    star: "4",
    banner: "Free",
    element: "Pyro",
    weapon: "Bow",
    type: "DPS/Sub-DPS",
    tier: "C",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Amber.png",
    altText: "Amber, the Outrider of Mondstadt",
  },
  {
    name: "Barbara",
    star: "4",
    banner: "All",
    element: "Hydro",
    weapon: "Catalyst",
    type: "Healer",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Barbara.png",
    altText: "Barbara, the Deaconess of the Church of Favonius",
  },
  {
    name: "Bennett",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Sword",
    type: "Support/DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Bennett.png",
    altText: "Bennett, the Adventurer from Mondstadt",
  },
  {
    name: "Diluc",
    star: "5",
    banner: "Standard",
    element: "Pyro",
    weapon: "Claymore",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Diluc.png",
    altText: "Diluc, the owner of Dawn Winery",
  },
  {
    name: "Diona",
    star: "4",
    banner: "All",
    element: "Cryo",
    weapon: "Bow",
    type: "Support/Healer",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Diona.png",
    altText: "Diona, the bartender of the Cat's Tail",
  },
  {
    name: "Eula",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Claymore",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Eula.png",
    altText: "Eula, the Spindrift Knight",
  },
  {
    name: "Fischl",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Bow",
    type: "Sub-DPS/Support",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Fischl.png",
    altText: "Fischl, the Prinzessin der Verurteilung",
  },
  {
    name: "Jean",
    star: "5",
    banner: "Standard",
    element: "Anemo",
    weapon: "Sword",
    type: "Support/Healer",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Jean.png",
    altText: "Jean, the Acting Grand Master of the Knights of Favonius",
  },
  {
    name: "Kaeya",
    star: "4",
    banner: "All",
    element: "Cryo",
    weapon: "Sword",
    type: "Sub-DPS/Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Kaeya.png",
    altText: "Kaeya, the Cavalry Captain",
  },
  {
    name: "Klee",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Catalyst",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Klee.png",
    altText: "Klee, the Spark Knight",
  },
  {
    name: "Lisa",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Catalyst",
    type: "Support/Sub-DPS",
    tier: "C",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Lisa.png",
    altText: "Lisa, the Librarian of the Knights of Favonius",
  },
  {
    name: "Mika",
    star: "4",
    banner: "All",
    element: "Cryo",
    weapon: "Polearm",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Mika.png",
    altText: "Mika, the surveyor of the Knights of Favonius",
  },
  {
    name: "Noelle",
    star: "4",
    banner: "All",
    element: "Geo",
    weapon: "Claymore",
    type: "DPS/Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Noelle.png",
    altText: "Noelle, the Maid Knight",
  },
  {
    name: "Razor",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Claymore",
    type: "DPS",
    tier: "C",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Razor.png",
    altText: "Razor, the wild boy of Mondstadt",
  },
  {
    name: "Rosaria",
    star: "4",
    banner: "All",
    element: "Cryo",
    weapon: "Polearm",
    type: "Sub-DPS/Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Rosaria.png",
    altText: "Rosaria, the Sister of Mondstadt",
  },
  {
    name: "Sucrose",
    star: "4",
    banner: "All",
    element: "Anemo",
    weapon: "Catalyst",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Sucrose.png",
    altText: "Sucrose, the assistant alchemist",
  },
  {
    name: "Venti",
    star: "5",
    banner: "Limited",
    element: "Anemo",
    weapon: "Bow",
    type: "Support/Sub-DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Venti.png",
    altText: "Venti, the Anemo Archon of Mondstadt",
  },
  // Liyue
  {
    name: "Beidou",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Claymore",
    type: "DPS/Sub-DPS",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Beidou.png",
    altText: "Beidou, the captain of The Crux",
  },
  {
    name: "Chongyun",
    star: "4",
    banner: "All",
    element: "Cryo",
    weapon: "Claymore",
    type: "DPS/Sub-DPS",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Chongyun.png",
    altText: "Chongyun, the exorcist from Liyue",
  },
  {
    name: "Ganyu",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Bow",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Ganyu.png",
    altText: "Ganyu, the half-qilin Adeptus",
  },
  {
    name: "Hu Tao",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Polearm",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Hu%20Tao.png",
    altText: "Hu Tao, the 77th Director of the Wangsheng Funeral Parlor",
  },
  {
    name: "Keqing",
    star: "5",
    banner: "Standard",
    element: "Electro",
    weapon: "Sword",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Keqing.png",
    altText: "Keqing, the Yuheng of the Liyue Qixing",
  },
  {
    name: "Ningguang",
    star: "4",
    banner: "All",
    element: "Geo",
    weapon: "Catalyst",
    type: "DPS/Support",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Ningguang.png",
    altText: "Ningguang, the Tianquan of the Liyue Qixing",
  },
  {
    name: "Qiqi",
    star: "5",
    banner: "Standard",
    element: "Cryo",
    weapon: "Sword",
    type: "Healer",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Qiqi.png",
    altText: "Qiqi, the zombie herbalist",
  },
  {
    name: "Shenhe",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Polearm",
    type: "Sub-DPS/Support",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Shenhe.png",
    altText: "Shenhe, the disciple of Cloud Retainer",
  },
  {
    name: "Xiangling",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Polearm",
    type: "DPS/Sub-DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Xiangling.png",
    altText: "Xiangling, the Head Chef at Wanmin Restaurant",
  },
  {
    name: "Xiao",
    star: "5",
    banner: "Limited",
    element: "Anemo",
    weapon: "Polearm",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Xiao.png",
    altText: "Xiao, the vigilant Yaksha",
  },
  {
    name: "Xingqiu",
    star: "4",
    banner: "All",
    element: "Hydro",
    weapon: "Sword",
    type: "Sub-DPS/Support",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Xingqiu.png",
    altText: "Xingqiu, the Guhua enthusiast",
  },
  {
    name: "Xinyan",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Claymore",
    type: "DPS",
    tier: "C",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Xinyan.png",
    altText: "Xinyan, the rock 'n' roll musician",
  },
  {
    name: "Yanfei",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Catalyst",
    type: "DPS",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Yanfei.png",
    altText: "Yanfei, the legal advisor in Liyue",
  },
  {
    name: "Yaoyao",
    star: "4",
    banner: "All",
    element: "Dendro",
    weapon: "Polearm",
    type: "Healer/Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Yaoyao.png",
    altText: "Yaoyao, the young assistant of Ganyu",
  },
  {
    name: "Yelan",
    star: "5",
    banner: "Limited",
    element: "Hydro",
    weapon: "Bow",
    type: "DPS/Sub-DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Yelan.png",
    altText: "Yelan, the mysterious intelligence officer",
  },
  {
    name: "Zhongli",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Polearm",
    type: "Support/DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Zhongli.png",
    altText: "Zhongli, the Geo Archon of Liyue",
  },
  // Inazuma 
  {
    name: "Arataki Itto",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Claymore",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Itto.png",
    altText: "Arataki Itto, the Oni leader of the Arataki Gang",
  },
  {
    name: "Gorou",
    star: "4",
    banner: "All",
    element: "Geo",
    weapon: "Bow",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Gorou.png",
    altText: "Gorou, the general of the resistance forces in Inazuma",
  },
  {
    name: "Kamisato Ayaka",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Sword",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Ayaka.png",
    altText: "Kamisato Ayaka, the elegant and graceful noblewoman of Inazuma",
  },
  {
    name: "Kamisato Ayato",
    star: "5",
    banner: "Limited",
    element: "Hydro",
    weapon: "Sword",
    type: "Support",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Ayato.png",
    altText: "Kamisato Ayato, the head of the Kamisato Clan and Yae Miko's older brother",
  },
  {
    name: "Kujou Sara",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Bow",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Sara.png",
    altText: "Kujou Sara, the General of the Tenryou Commission",
  },
  {
    name: "Kuki Shinobu",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Sword",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Kuki%20Shinobu.png",
    altText: "Kuki Shinobu, the Yashiro Commission's trusty secretary",
  },
  {
    name: "Raiden Shogun",
    star: "5",
    banner: "Limited",
    element: "Electro",
    weapon: "Polearm",
    type: "DPS/Sub-DPS/Support",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Raiden.png",
    altText: "Raiden Shogun, the Electro Archon of Inazuma",
  },
  {
    name: "Sangonomiya Kokomi",
    star: "5",
    banner: "Limited",
    element: "Hydro",
    weapon: "Catalyst",
    type: "Healer/Support",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Kokomi.png",
    altText: "Sangonomiya Kokomi, the Divine Priestess of Watatsumi Island",
  },
  {
    name: "Sayu",
    star: "4",
    banner: "All",
    element: "Anemo",
    weapon: "Claymore",
    type: "Sub-DPS",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Sayu.png",
    altText: "Sayu, the carefree ninja of Inazuma",
  },
  {
    name: "Shikanoin Heizou",
    star: "5",
    banner: "Limited",
    element: "Anemo",
    weapon: "Catalyst",
    type: "Support/Sub-DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Heizou.png",
    altText: "Shikanoin Heizou, the detective of Inazuma",
  },
  {
    name: "Thoma",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Polearm",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Thoma.png",
    altText: "Thoma, the steadfast housekeeper of the Kamisato Clan",
  },
  {
    name: "Yae Miko",
    star: "5",
    banner: "Limited",
    element: "Electro",
    weapon: "Catalyst",
    type: "DPS/Sub-DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Yae%20Miko.png",
    altText: "Yae Miko, the Guuji of the Grand Narukami Shrine",
  },
  {
    name: "Yoimiya",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Bow",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Yoimiya.png",
    altText: "Yoimiya, the Queen of the Summer Festival",
  },
  // Sumeru
  {
    name: "Alhaitham",
    star: "5",
    banner: "Limited",
    element: "Dendro",
    weapon: "Sword",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Alhaitham.png",
    altText: "Alhaitham, the Scribe of the Akademiya"
  },
  {
    name: "Candace",
    star: "4",
    banner: "Limited",
    element: "Hydro",
    weapon: "Polearm",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Candace.png",
    altText: "Candace, the Protector of the Oasis"
  },
  {
    name: "Collei",
    star: "4",
    banner: "Standard",
    element: "Dendro",
    weapon: "Bow",
    type: "Support",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Collei.png",
    altText: "Collei, the Outcast of the Forest"
  },
  {
    name: "Cyno",
    star: "5",
    banner: "Limited",
    element: "Electro",
    weapon: "Polearm",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Cyno.png",
    altText: "Cyno, the General Mahamatra"
  },
  {
    name: "Dehya",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Claymore",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Dehya.png",
    altText: "Dehya, the Flame-Mane of the Desert"
  },
  {
    name: "Faruzan",
    star: "4",
    banner: "Limited",
    element: "Anemo",
    weapon: "Bow",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Faruzan.png",
    altText: "Faruzan, the Scholar of the Desert"
  },
  {
    name: "Kaveh",
    star: "5",
    banner: "Limited",
    element: "Dendro",
    weapon: "Sword",
    type: "Support",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Kaveh.png",
    altText: "Kaveh, the Architect"
  },
  {
    name: "Layla",
    star: "4",
    banner: "Standard",
    element: "Cryo",
    weapon: "Sword",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Layla.png",
    altText: "Layla, the Guardian of the Night"
  },
  {
    name: "Nahida",
    star: "5",
    banner: "Limited",
    element: "Dendro",
    weapon: "Catalyst",
    type: "Support",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Nahida.png",
    altText: "Nahida, the Dendro Archon"
  },
  {
    name: "Tighnari",
    star: "5",
    banner: "Limited",
    element: "Dendro",
    weapon: "Bow",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Tighnari.png",
    altText: "Tighnari, the Forest Watcher"
  },
  {
    name: "Sethos",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Catalyst",
    type: "Support",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Sethos.png",
    altText: "Sethos, the Seer of the Sands"
  },
  // Fontaine
  {
    name: "Lynette",
    star: "4",
    banner: "Limited",
    element: "Anemo",
    weapon: "Sword",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Lynette.png",
    altText: "Lynette, the Swift Messenger"
  },
  {
    name: "Lyney",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Bow",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Lyney.png",
    altText: "Lyney, the Great Illusionist"
  },
  {
    name: "Navia",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Claymore",
    type: "Support",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Lyney.png",
    altText: "Navia, the Lady of the Eternal Court"
  },
  {
    name: "Freminet",
    star: "4",
    banner: "Limited",
    element: "Cryo",
    weapon: "Claymore",
    type: "DPS",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Freminet.png",
    altText: "Freminet, the Young Excavator"
  },
  {
    name: "Furina",
    star: "5",
    banner: "Limited",
    element: "Hydro",
    weapon: "Sword",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Furina.png",
    altText: "Furina, the Sovereign of Justice"
  },
  {
    name: "Wriothesley",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Catalyst",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Wriothesley.png",
    altText: "Wriothesley, the Silent Arbitrator"
  },
  {
    name: "Chevreuse",
    star: "4",
    banner: "Limited",
    element: "Hydro",
    weapon: "Polearm",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Chevreuse.png",
    altText: "Chevreuse, the Loyal Companion"
  },
  // Natlan 
  {
    name: "Mualani",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Bow",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Mualani.png",
    altText: "Mualani, the Flame of Natlan"
  },
  {
    name: "Kinich",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Claymore",
    type: "DPS",
    tier: "A",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Kinich.png",
    altText: "Kinich, the God of the Sun"
  },
  {
    name: "Xilonen",
    star: "5",
    banner: "Limited",
    element: "Electro",
    weapon: "Sword",
    type: "Support",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Xilonen.png",
    altText: "Xilonen, the Goddess of the Earth"
  },
  {
    name: "Kachina",
    star: "4",
    banner: "Limited",
    element: "Hydro",
    weapon: "Bow",
    type: "Support",
    tier: "B",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Kachina.png",
    altText: "Kachina, the Spirit of the Waters"
  },

  // Fatui
  {
    name: "Arlecchino",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Sword",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Arlecchino.png",
    altText: "Arlecchino, the Harlequin of Snezhnaya"
  },
  {
    name: "Tartaglia",
    star: "5",
    banner: "Limited",
    element: "Hydro",
    weapon: "Bow",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Childe.png",
    altText: "Tartaglia (Childe), the 11th Fatui Harbinger"
  },
  {
    name: "Wanderer",
    star: "5",
    banner: "Limited",
    element: "Anemo",
    weapon: "Catalyst",
    type: "DPS",
    tier: "S",
    image: "https://rerollcdn.com/GENSHIN/Characters/1/Wanderer.png",
    altText: "Wanderer, the Scaramouche"
  }
];

export { genshinCharacters };
