const genshinCharacters = [
  // Mondstadt
  {
    name: "Albedo",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Sword",
    type: "DPS/Sub-DPS",
    tier: "A",
    image: "https://example.com/albedo.jpg",
    altText: "Albedo, the Chief Alchemist of the Knights of Favonius",
  },
  {
    name: "Amber",
    star: "4",
    banner: "Free",
    element: "Pyro",
    weapon: "Bow",
    type: "DPS/Sub-DPS",
    tier: "C",
    image: "https://example.com/amber.jpg",
    altText: "Amber, the Outrider of Mondstadt",
  },
  {
    name: "Barbara",
    star: "4",
    banner: "All",
    element: "Hydro",
    weapon: "Catalyst",
    type: "Healer",
    tier: "B",
    image: "https://example.com/barbara.jpg",
    altText: "Barbara, the Deaconess of the Church of Favonius",
  },
  {
    name: "Bennett",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Sword",
    type: "Support/DPS",
    tier: "S",
    image: "https://example.com/bennett.jpg",
    altText: "Bennett, the Adventurer from Mondstadt",
  },
  {
    name: "Diluc",
    star: "5",
    banner: "Standard",
    element: "Pyro",
    weapon: "Claymore",
    type: "DPS",
    tier: "A",
    image: "https://example.com/diluc.jpg",
    altText: "Diluc, the owner of Dawn Winery",
  },
  {
    name: "Diona",
    star: "4",
    banner: "All",
    element: "Cryo",
    weapon: "Bow",
    type: "Support/Healer",
    tier: "A",
    image: "https://example.com/diona.jpg",
    altText: "Diona, the bartender of the Cat's Tail",
  },
  {
    name: "Eula",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Claymore",
    type: "DPS",
    tier: "A",
    image: "https://example.com/eula.jpg",
    altText: "Eula, the Spindrift Knight",
  },
  {
    name: "Fischl",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Bow",
    type: "Sub-DPS/Support",
    tier: "A",
    image: "https://example.com/fischl.jpg",
    altText: "Fischl, the Prinzessin der Verurteilung",
  },
  {
    name: "Jean",
    star: "5",
    banner: "Standard",
    element: "Anemo",
    weapon: "Sword",
    type: "Support/Healer",
    tier: "A",
    image: "https://example.com/jean.jpg",
    altText: "Jean, the Acting Grand Master of the Knights of Favonius",
  },
  {
    name: "Kaeya",
    star: "4",
    banner: "All",
    element: "Cryo",
    weapon: "Sword",
    type: "Sub-DPS/Support",
    tier: "B",
    image: "https://example.com/kaeya.jpg",
    altText: "Kaeya, the Cavalry Captain",
  },
  {
    name: "Klee",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Catalyst",
    type: "DPS",
    tier: "A",
    image: "https://example.com/klee.jpg",
    altText: "Klee, the Spark Knight",
  },
  {
    name: "Lisa",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Catalyst",
    type: "Support/Sub-DPS",
    tier: "C",
    image: "https://example.com/lisa.jpg",
    altText: "Lisa, the Librarian of the Knights of Favonius",
  },
  {
    name: "Mika",
    star: "4",
    banner: "All",
    element: "Cryo",
    weapon: "Polearm",
    type: "Support",
    tier: "B",
    image: "https://example.com/mika.jpg",
    altText: "Mika, the surveyor of the Knights of Favonius",
  },
  {
    name: "Noelle",
    star: "4",
    banner: "All",
    element: "Geo",
    weapon: "Claymore",
    type: "DPS/Support",
    tier: "B",
    image: "https://example.com/noelle.jpg",
    altText: "Noelle, the Maid Knight",
  },
  {
    name: "Razor",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Claymore",
    type: "DPS",
    tier: "C",
    image: "https://example.com/razor.jpg",
    altText: "Razor, the wild boy of Mondstadt",
  },
  {
    name: "Rosaria",
    star: "4",
    banner: "All",
    element: "Cryo",
    weapon: "Polearm",
    type: "Sub-DPS/Support",
    tier: "B",
    image: "https://example.com/rosaria.jpg",
    altText: "Rosaria, the Sister of Mondstadt",
  },
  {
    name: "Sucrose",
    star: "4",
    banner: "All",
    element: "Anemo",
    weapon: "Catalyst",
    type: "Support",
    tier: "B",
    image: "https://example.com/sucrose.jpg",
    altText: "Sucrose, the assistant alchemist",
  },
  {
    name: "Venti",
    star: "5",
    banner: "Limited",
    element: "Anemo",
    weapon: "Bow",
    type: "Support/Sub-DPS",
    tier: "A",
    image: "https://example.com/venti.jpg",
    altText: "Venti, the Anemo Archon of Mondstadt",
  },
  // Liyue
  {
    name: "Beidou",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Claymore",
    type: "DPS/Sub-DPS",
    tier: "B",
    image: "https://example.com/beidou.jpg",
    altText: "Beidou, the captain of The Crux",
  },
  {
    name: "Chongyun",
    star: "4",
    banner: "All",
    element: "Cryo",
    weapon: "Claymore",
    type: "DPS/Sub-DPS",
    tier: "B",
    image: "https://example.com/chongyun.jpg",
    altText: "Chongyun, the exorcist from Liyue",
  },
  {
    name: "Ganyu",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Bow",
    type: "DPS",
    tier: "S",
    image: "https://example.com/ganyu.jpg",
    altText: "Ganyu, the half-qilin Adeptus",
  },
  {
    name: "Hu Tao",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Polearm",
    type: "DPS",
    tier: "S",
    image: "https://example.com/hutao.jpg",
    altText: "Hu Tao, the 77th Director of the Wangsheng Funeral Parlor",
  },
  {
    name: "Keqing",
    star: "5",
    banner: "Standard",
    element: "Electro",
    weapon: "Sword",
    type: "DPS",
    tier: "A",
    image: "https://example.com/keqing.jpg",
    altText: "Keqing, the Yuheng of the Liyue Qixing",
  },
  {
    name: "Ningguang",
    star: "4",
    banner: "All",
    element: "Geo",
    weapon: "Catalyst",
    type: "DPS/Support",
    tier: "A",
    image: "https://example.com/ningguang.jpg",
    altText: "Ningguang, the Tianquan of the Liyue Qixing",
  },
  {
    name: "Qiqi",
    star: "5",
    banner: "Standard",
    element: "Cryo",
    weapon: "Sword",
    type: "Healer",
    tier: "B",
    image: "https://example.com/qiqi.jpg",
    altText: "Qiqi, the zombie herbalist",
  },
  {
    name: "Shenhe",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Polearm",
    type: "Sub-DPS/Support",
    tier: "A",
    image: "https://example.com/shenhe.jpg",
    altText: "Shenhe, the disciple of Cloud Retainer",
  },
  {
    name: "Xiangling",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Polearm",
    type: "DPS/Sub-DPS",
    tier: "A",
    image: "https://example.com/xiangling.jpg",
    altText: "Xiangling, the Head Chef at Wanmin Restaurant",
  },
  {
    name: "Xiao",
    star: "5",
    banner: "Limited",
    element: "Anemo",
    weapon: "Polearm",
    type: "DPS",
    tier: "A",
    image: "https://example.com/xiao.jpg",
    altText: "Xiao, the vigilant Yaksha",
  },
  {
    name: "Xingqiu",
    star: "4",
    banner: "All",
    element: "Hydro",
    weapon: "Sword",
    type: "Sub-DPS/Support",
    tier: "A",
    image: "https://example.com/xingqiu.jpg",
    altText: "Xingqiu, the Guhua enthusiast",
  },
  {
    name: "Xinyan",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Claymore",
    type: "DPS",
    tier: "C",
    image: "https://example.com/xinyan.jpg",
    altText: "Xinyan, the rock 'n' roll musician",
  },
  {
    name: "Yanfei",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Catalyst",
    type: "DPS",
    tier: "B",
    image: "https://example.com/yanfei.jpg",
    altText: "Yanfei, the legal advisor in Liyue",
  },
  {
    name: "Yaoyao",
    star: "4",
    banner: "All",
    element: "Dendro",
    weapon: "Polearm",
    type: "Healer/Support",
    tier: "B",
    image: "https://example.com/yaoyao.jpg",
    altText: "Yaoyao, the young assistant of Ganyu",
  },
  {
    name: "Yelan",
    star: "5",
    banner: "Limited",
    element: "Hydro",
    weapon: "Bow",
    type: "DPS/Sub-DPS",
    tier: "A",
    image: "https://example.com/yelan.jpg",
    altText: "Yelan, the mysterious intelligence officer",
  },
  {
    name: "Zhongli",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Polearm",
    type: "Support/DPS",
    tier: "S",
    image: "https://example.com/zhongli.jpg",
    altText: "Zhongli, the Geo Archon of Liyue",
  },
  // Inazuma 
  {
    name: "Arataki Itto",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Claymore",
    type: "DPS",
    tier: "A",
    image: "https://example.com/arataki_itto.jpg",
    altText: "Arataki Itto, the Oni leader of the Arataki Gang",
  },
  {
    name: "Gorou",
    star: "4",
    banner: "All",
    element: "Geo",
    weapon: "Bow",
    type: "Support",
    tier: "B",
    image: "https://example.com/gorou.jpg",
    altText: "Gorou, the general of the resistance forces in Inazuma",
  },
  {
    name: "Kamisato Ayaka",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Sword",
    type: "DPS",
    tier: "A",
    image: "https://example.com/kamisato_ayaka.jpg",
    altText: "Kamisato Ayaka, the elegant and graceful noblewoman of Inazuma",
  },
  {
    name: "Kamisato Ayato",
    star: "5",
    banner: "Limited",
    element: "Hydro",
    weapon: "Sword",
    type: "Support",
    tier: "A",
    image: "https://example.com/kamisato_ayato.jpg",
    altText: "Kamisato Ayato, the head of the Kamisato Clan and Yae Miko's older brother",
  },
  {
    name: "Kujou Sara",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Bow",
    type: "Support",
    tier: "B",
    image: "https://example.com/kujousara.jpg",
    altText: "Kujou Sara, the General of the Tenryou Commission",
  },
  {
    name: "Kuki Shinobu",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Sword",
    type: "Support",
    tier: "B",
    image: "https://example.com/kukishinobu.jpg",
    altText: "Kuki Shinobu, the Yashiro Commission's trusty secretary",
  },
  {
    name: "Raiden Shogun",
    star: "5",
    banner: "Limited",
    element: "Electro",
    weapon: "Polearm",
    type: "DPS/Sub-DPS/Support",
    tier: "S",
    image: "https://example.com/raiden_shogun.jpg",
    altText: "Raiden Shogun, the Electro Archon of Inazuma",
  },
  {
    name: "Sangonomiya Kokomi",
    star: "5",
    banner: "Limited",
    element: "Hydro",
    weapon: "Catalyst",
    type: "Healer/Support",
    tier: "A",
    image: "https://example.com/sangonomiya_kokomi.jpg",
    altText: "Sangonomiya Kokomi, the Divine Priestess of Watatsumi Island",
  },
  {
    name: "Sayu",
    star: "4",
    banner: "All",
    element: "Anemo",
    weapon: "Claymore",
    type: "Sub-DPS",
    tier: "B",
    image: "https://example.com/sayu.jpg",
    altText: "Sayu, the carefree ninja of Inazuma",
  },
  {
    name: "Shikanoin Heizou",
    star: "5",
    banner: "Limited",
    element: "Anemo",
    weapon: "Catalyst",
    type: "Support/Sub-DPS",
    tier: "A",
    image: "https://example.com/shikanoin_heizou.jpg",
    altText: "Shikanoin Heizou, the detective of Inazuma",
  },
  {
    name: "Thoma",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Polearm",
    type: "Support",
    tier: "B",
    image: "https://example.com/thoma.jpg",
    altText: "Thoma, the steadfast housekeeper of the Kamisato Clan",
  },
  {
    name: "Yae Miko",
    star: "5",
    banner: "Limited",
    element: "Electro",
    weapon: "Catalyst",
    type: "DPS/Sub-DPS",
    tier: "A",
    image: "https://example.com/yae_miko.jpg",
    altText: "Yae Miko, the Guuji of the Grand Narukami Shrine",
  },
  {
    name: "Yoimiya",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Bow",
    type: "DPS",
    tier: "A",
    image: "https://example.com/yoimiya.jpg",
    altText: "Yoimiya, the Queen of the Summer Festival",
  },
  // Sumeru
  {
    name: "Alhaitham",
    star: "5",
    banner: "Limited",
    element: "Dendro",
    weapon: "Sword",
    type: "DPS",
    tier: "S",
    image: "https://example.com/alhaitham.jpg",
    altText: "Alhaitham, the Scribe of the Akademiya"
  },
  {
    name: "Candace",
    star: "4",
    banner: "Limited",
    element: "Hydro",
    weapon: "Polearm",
    type: "Support",
    tier: "B",
    image: "https://example.com/candace.jpg",
    altText: "Candace, the Protector of the Oasis"
  },
  {
    name: "Collei",
    star: "4",
    banner: "Standard",
    element: "Dendro",
    weapon: "Bow",
    type: "Support",
    tier: "A",
    image: "https://example.com/collei.jpg",
    altText: "Collei, the Outcast of the Forest"
  },
  {
    name: "Cyno",
    star: "5",
    banner: "Limited",
    element: "Electro",
    weapon: "Polearm",
    type: "DPS",
    tier: "A",
    image: "https://example.com/cyno.jpg",
    altText: "Cyno, the General Mahamatra"
  },
  {
    name: "Dehya",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Claymore",
    type: "DPS",
    tier: "S",
    image: "https://example.com/dehya.jpg",
    altText: "Dehya, the Flame-Mane of the Desert"
  },
  {
    name: "Faruzan",
    star: "4",
    banner: "Limited",
    element: "Anemo",
    weapon: "Bow",
    type: "Support",
    tier: "B",
    image: "https://example.com/faruzan.jpg",
    altText: "Faruzan, the Scholar of the Desert"
  },
  {
    name: "Kaveh",
    star: "5",
    banner: "Limited",
    element: "Dendro",
    weapon: "Sword",
    type: "Support",
    tier: "A",
    image: "https://example.com/kaveh.jpg",
    altText: "Kaveh, the Architect"
  },
  {
    name: "Layla",
    star: "4",
    banner: "Standard",
    element: "Cryo",
    weapon: "Sword",
    type: "Support",
    tier: "B",
    image: "https://example.com/layla.jpg",
    altText: "Layla, the Guardian of the Night"
  },
  {
    name: "Nahida",
    star: "5",
    banner: "Limited",
    element: "Dendro",
    weapon: "Catalyst",
    type: "Support",
    tier: "S",
    image: "https://example.com/nahida.jpg",
    altText: "Nahida, the Dendro Archon"
  },
  {
    name: "Tighnari",
    star: "5",
    banner: "Limited",
    element: "Dendro",
    weapon: "Bow",
    type: "DPS",
    tier: "S",
    image: "https://example.com/tighnari.jpg",
    altText: "Tighnari, the Forest Watcher"
  },
  {
    name: "Sethos",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Catalyst",
    type: "Support",
    tier: "A",
    image: "https://example.com/sethos.jpg",
    altText: "Sethos, the Seer of the Sands"
  },
  // Fontaine
  {
    name: "Lynette",
    star: "4",
    banner: "Limited",
    element: "Anemo",
    weapon: "Sword",
    type: "Support",
    tier: "B",
    image: "https://example.com/lynette.jpg",
    altText: "Lynette, the Swift Messenger"
  },
  {
    name: "Lyney",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Bow",
    type: "DPS",
    tier: "S",
    image: "https://example.com/lyney.jpg",
    altText: "Lyney, the Great Illusionist"
  },
  {
    name: "Navia",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Claymore",
    type: "Support",
    tier: "A",
    image: "https://example.com/navia.jpg",
    altText: "Navia, the Lady of the Eternal Court"
  },
  {
    name: "Freminet",
    star: "4",
    banner: "Limited",
    element: "Cryo",
    weapon: "Claymore",
    type: "DPS",
    tier: "B",
    image: "https://example.com/freminet.jpg",
    altText: "Freminet, the Young Excavator"
  },
  {
    name: "Furina",
    star: "5",
    banner: "Limited",
    element: "Hydro",
    weapon: "Sword",
    type: "DPS",
    tier: "S",
    image: "https://example.com/furina.jpg",
    altText: "Furina, the Sovereign of Justice"
  },
  {
    name: "Wriothesley",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Catalyst",
    type: "DPS",
    tier: "A",
    image: "https://example.com/wriothesley.jpg",
    altText: "Wriothesley, the Silent Arbitrator"
  },
  {
    name: "Chevreuse",
    star: "4",
    banner: "Limited",
    element: "Hydro",
    weapon: "Polearm",
    type: "Support",
    tier: "B",
    image: "https://example.com/chevreuse.jpg",
    altText: "Chevreuse, the Loyal Companion"
  },
  // Natlan 
  {
    name: "Mualani",
    star: "5",
    banner: "Limited",
    element: "Pyro",
    weapon: "Bow",
    type: "DPS",
    tier: "S",
    image: "https://example.com/mualani.jpg",
    altText: "Mualani, the Flame of Natlan"
  },
  {
    name: "Kinich",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Claymore",
    type: "DPS",
    tier: "A",
    image: "https://example.com/kinich.jpg",
    altText: "Kinich, the God of the Sun"
  },
  {
    name: "Xilonen",
    star: "5",
    banner: "Limited",
    element: "Electro",
    weapon: "Sword",
    type: "Support",
    tier: "S",
    image: "https://example.com/xilonen.jpg",
    altText: "Xilonen, the Goddess of the Earth"
  },
  {
    name: "Kachina",
    star: "4",
    banner: "Limited",
    element: "Hydro",
    weapon: "Bow",
    type: "Support",
    tier: "B",
    image: "https://example.com/kachina.jpg",
    altText: "Kachina, the Spirit of the Waters"
  },

  // Fatui
  {
    name: "Arlecchino",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Sword",
    type: "DPS",
    tier: "S",
    image: "https://example.com/arlecchino.jpg",
    altText: "Arlecchino, the Harlequin of Snezhnaya"
  },
  {
    name: "Tartaglia",
    star: "5",
    banner: "Limited",
    element: "Hydro",
    weapon: "Bow",
    type: "DPS",
    tier: "S",
    image: "https://example.com/tartaglia.jpg",
    altText: "Tartaglia (Childe), the 11th Fatui Harbinger"
  },
  {
    name: "Wanderer",
    star: "5",
    banner: "Limited",
    element: "Anemo",
    weapon: "Catalyst",
    type: "DPS",
    tier: "S",
    image: "https://example.com/wanderer.jpg",
    altText: "Wanderer, the Scaramouche"
  }
];

export { genshinCharacters };
