const genshinCharacters = [
  {
    name: "Lumine",
    star: "5",
    banner: "Free",
    element: "Anemo",
    weapon: "Sword",
    type: "DPS/Sub-DPS",
    tier: "D",
    image: "https://example.com/lumine.jpg",
    altText: "Lumine, the Traveler from Genshin Impact",
  },
  {
    name: "Aether",
    star: "5",
    banner: "Free",
    element: "Geo",
    weapon: "Sword",
    type: "Sub-DPS/Support",
    tier: "C",
    image: "https://example.com/aether.jpg",
    altText: "Aether, the Traveler from Genshin Impact",
  },
  {
    name: "Amber",
    star: "4",
    banner: "Free",
    element: "Pyro",
    weapon: "Bow",
    type: "DPS/Sub-DPS",
    tier: "C",
    image: "https://example.com/amber.jpg",
    altText: "Amber, the Outrider of Mondstadt",
  },
  {
    name: "Venti",
    star: "5",
    banner: "Limited",
    element: "Anemo",
    weapon: "Bow",
    type: "Sub-DPS/Support",
    tier: "B",
    image: "https://example.com/venti.jpg",
    altText: "Venti, the Anemo Archon",
  },
  {
    name: "Zhongli",
    star: "5",
    banner: "Limited",
    element: "Geo",
    weapon: "Polearm",
    type: "Sub-DPS/Support",
    tier: "A",
    image: "https://example.com/zhongli.jpg",
    altText: "Zhongli, the Geo Archon",
  },
  {
    name: "Diluc",
    star: "5",
    banner: "Standard",
    element: "Pyro",
    weapon: "Claymore",
    type: "DPS",
    tier: "B",
    image: "https://example.com/diluc.jpg",
    altText: "Diluc, the owner of Dawn Winery",
  },
  {
    name: "Fischl",
    star: "4",
    banner: "All",
    element: "Electro",
    weapon: "Bow",
    type: "Sub-DPS/Support",
    tier: "A",
    image: "https://example.com/fischl.jpg",
    altText: "Fischl, the Prinzessin der Verurteilung",
  },
  {
    name: "Mona",
    star: "5",
    banner: "Standard",
    element: "Hydro",
    weapon: "Catalyst",
    type: "Sub-DPS/Support",
    tier: "A",
    image: "https://example.com/mona.jpg",
    altText: "Mona, the Astrologist",
  },
  {
    name: "Xingqiu",
    star: "4",
    banner: "All",
    element: "Hydro",
    weapon: "Sword",
    type: "Sub-DPS/Support",
    tier: "B",
    image: "https://example.com/xingqiu.jpg",
    altText: "Xingqiu, the 11th of the Feiyun Commerce Guild",
  },
  {
    name: "Xinyan",
    star: "4",
    banner: "All",
    element: "Pyro",
    weapon: "Claymore",
    type: "Sub-DPS",
    tier: "F",
    image: "https://example.com/xinyan.jpg",
    altText: "Xinyan, the rock 'n' roll musician",
  },
  {
    name: "Keqing",
    star: "5",
    banner: "Standard",
    element: "Electro",
    weapon: "Sword",
    type: "DPS",
    tier: "B",
    image: "https://example.com/keqing.jpg",
    altText: "Keqing, the Yuheng of the Liyue Qixing",
  },
  {
    name: "Ganyu",
    star: "5",
    banner: "Limited",
    element: "Cryo",
    weapon: "Bow",
    type: "DPS/Sub-DPS",
    tier: "A",
    image: "https://example.com/ganyu.jpg",
    altText: "Ganyu, the half-qilin Adeptus",
  },
  {
    name: "Raiden Shogun",
    star: "5",
    banner: "Limited",
    element: "Electro",
    weapon: "Polearm",
    type: "DPS/Sub-DPS/Support",
    tier: "S",
    image: "https://example.com/raiden_shogun.jpg",
    altText: "Raiden Shogun, the Electro Archon",
  },
];

export {genshinCharacters};